### ISSUE TITLE
🔨 file-to-file transpilation

### ISSUE THREAD

**Issue by unicornware** [flex-development/mkbuild#2]
### Prerequisites

- [X] i am a project maintainer

### Proposed work

implementing file-to-file transpilation.

### Success criteria

- [x] `config`
  - [x] `defineBuildConfig`
    - [x] implementation
      - [x] return `config` argument
    - [x] tests
  - [x] `esLoader`
    - [x] implementation
      - [x] return build config from `.cts` file
      - [x] return build config from `.js` file
      - [x] return build config from `.mjs` file
      - [x] return build config from `.mts` file
      - [x] return build config from `.ts` file
    - [x] tests
  - [x] `loadBuildConfig`
    - [x] implementation
      - [x] [`cosmiconfig`][1] integration
      - [x] search for `build.config.{cjs,cts,js,json,mjs,mts,ts}`
      - [x] return config object if config file is found 
      - [x] return empty object if config file is not found 
    - [x] tests
- [x] `make`
  - [x] implementation
    - [x] determine current working directory
      - [x] resolve `options.cwd` relative to `process.cwd()`
    - [x] load build config from current working directory
    - [x] merge `build.config.{cjs,cts,js,json,mjs,mts,ts}`, `config` argument, and default options
      - [x] give priority to `build.config.{cjs,cts,js,json,mjs,mts,ts}`
    - [x] load `package.json` from current working directory
    - [x] normalize build entry options
      - [x] default `outdir` to `options.outdir`
      - [x] default `source` to `src`
      - [x] default `format` to `esm`
      - [x] default `ext` to `entry.ext ?? (entry.format === 'esm' ? '.mjs' : '.js')`
      - [x] default `declaration` to `(entry.declaration ?? declaration) && entry.format !== 'iife'`
    - [x] print build start info
    - [x] clean output directories
    - [x] process build entries
      - [x] filter input files
      - [x] build source files
      - [x] write output files
    - [x] print build done info
    - [x] print build analysis
    - [x] print total build size
  - [x] tests
- [x] `plugins`
  - [x] `dts`
    - [x] implementation
      - [x] generate typescript declarations
    - [x] tests
  - [x] `fully-specified`
    - [x] implementation
      - [x] do nothing if bundling
      - [x] add file extensions to bare specifiers in output file content
      - [x] add file extensions to relative specifiers in output file content
    - [x] tests
  - [x] `tsconfig-paths`
    - [x] implementation
      - [x] do nothing if bundling
      - [x] resolve path aliases in output file content
    - [x] tests
- [x] `utils`
  - [x] `analyzeResults`
    - [x] implementation
        - [x] pretty print build results
    - [x] tests
  - [x] `esbuilder`
    - [x] implementation
      - [x] build source files with [ebuild build api][2]
        - [x] skip build if source file extension does not match `ESBUILDER_REGEX`
        - [x] sanitize build api options
        - [x] push plugins
            1. `dts`
                - [x] if `entry.declaration` is `true`
            2. `tsconfig-paths`
                - [x] if `options.esbuild.tsconfig` or `process.env.TS_NODE_PROJECT` is truthy
            3. `fully-specified`
                - [x] if build entry format is `esm` or build entry extension is `.cjs`
    - [x] tests
  - [x] `extractStatements`
    - [x] implementation
        - [x] extract `export` statements
        - [x] extract `import` statements
        - [x] extract `require` statements
    - [x] tests
  - [x] `write`
    - [x] implementation
        - [x] write build result to file system
    - [x] tests

### Related documents

- [`colorette`][3]
- [`consola`][4]
- [`globby`][5]
- [`mlly`][6]
- [`pretty-bytes`][7]
- [`tsconfig-paths`][8]

### Additional context

- [`findExports`][9] cannot find type exports (`export type`) or exports in declaration files (`export declare`) 🙃
  - ~~[`patch-package`][10] will be used to apply a patch in production environments~~

### Linked issues

N/A

[1]: https://github.com/davidtheclark/cosmiconfig
[2]: https://esbuild.github.io/api/#build-api
[3]: https://github.com/jorgebucaran/colorette
[4]: https://github.com/unjs/consola
[5]: https://github.com/sindresorhus/globby
[6]: https://github.com/unjs/mlly
[7]: https://github.com/sindresorhus/pretty-bytes
[8]: https://github.com/dividab/tsconfig-paths
[9]: https://github.com/unjs/mlly/tree/v0.5.14#findexports
[10]: https://github.com/ds300/patch-package
