### ISSUE TITLE
🔨 bundling

### ISSUE THREAD

**Issue by unicornware** [flex-development/mkbuild#9]
### Prerequisites

- [X] i am a project maintainer

### Proposed work

implementing bundle support via the [esbuild build api][1].

### Success criteria

- [x] `interfaces`
  - [x] `Entry`
    - [x] `bundle?` - enable bundling
    - [x] `name?` - bundle output file name
- [x] `make`
  - [x] refactor to support bundling
  - [x] update tests
- [x] `patches`
  - ~`dts-bundle-generator+6.13.0.patch`~
- [x] `plugins`
  - [x] `dts`
    - [x] refactor to simplify logic
    - ~generate bundled declaration files~
- [x] `utils`
  - [x] `esbuilder`
    - [x] refactor [`loader`][2] configuration
      - [x] pick loader based on `entry.format` and/or `entry.bundle`
        - note: some files should be copied during transpilation, but not when bundling. e.g: json files
    - [x] refactor to support `Entry.name?`
    - [x] refactor to support esbuild bundling and code splitting options
      - [x] [`assetNames`][3]
      - [x] [`bundle`][4]
      - [x] [`chunkNames`][5]
      - [x] [`external`][6]
      - [x] [`splitting`][7]
    - [x] update tests

### Related documents

- [`dts-bundle-generator`][8]
- [`rollup-plugin-dts`][9]

### Additional context

- `dts-bundle-generator@6.13.0` includes `typescript` as a dependency instead of a peer dependency
  - a patch will be applied to correct this
- Microsoft/TypeScript#4433

### Linked issues

N/A

[1]: https://esbuild.github.io/api/#build-api
[2]: https://esbuild.github.io/api/#loader
[3]: https://esbuild.github.io/api/#asset-names
[4]: https://esbuild.github.io/api/#bundle
[5]: https://esbuild.github.io/api/#chunk-names
[6]: https://esbuild.github.io/api/#external
[7]: https://esbuild.github.io/api/#splitting
[8]: https://github.com/timocov/dts-bundle-generator/tree/v6.13.0
[9]: https://github.com/Swatinem/rollup-plugin-dts
